# Generated by Django 4.1.3 on 2023-01-14 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at', 'updated_at')},
        ),
        migrations.AlterField(
            model_name='chat',
            name='reactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactoe', to=settings.AUTH_USER_MODEL),
        ),
    ]
